name: Specs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11.5
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: eregon/use-ruby-action@master # this will use by default the .ruby-version file in your repository
      - name: Install PostgreSQL 11 client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/car_crud_with_piechart_test
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rspec
